### ISSUE TITLE
Bug: Error handling in `listIntroductionPeers(pagination: Pagination?)` function

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-ios#177] opened 2023-10-25 12:50 UTC
### Describe the bug

While debugging, an error log was noticed that originates from the `listIntroductionPeers(pagination: Pagination?)` function in the `Conversations` class. The error is caught and printed, but not rethrown, which prevents it from being handled by the client. This issue is to discuss whether this behavior is expected and if any changes are needed.

![Screenshot 2023-10-25 at 13 08 34](https://github.com/xmtp/xmtp-ios/assets/1447073/5640b4dd-2234-443e-8956-ab9360d0d81f)

### Steps to reproduce the bug

The error is triggered when calling `Conversations.list()`. The error message is 
`"Loading introduction from peers: queryError("query")".`

The relevant code is in the listIntroductionPeers(pagination: Pagination?) function:

`Sources/XMTP/Conversations.swift
startLine: 247
endLine: 273`

**Comment by daria-github** [comment] 2023-11-02 17:55
Closing, as intended -- if there’s bad data in an introduction message then we don’t want to break loading the rest of the introduction messages. Will reopen if this logic creates any issues.

**Closed by daria-github** 2023-11-02 17:55 UTC
Labels: bug
